logging:
  file:
    name: ${spring.application.name}
  config: classpath:log4j2.yml

server:
  port: 8083
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 1024
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 16
      worker: 256

spring:
  application:
    name: eden-demo-mvc
  profiles:
    active: local # 默认启用开发环境
  data:
    redis:
      repositories:
        enabled: true
  datasource: # 数据源
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 5000
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 300000
      maxLifetime: 1200000
  redis: # 缓存数据库
    lettuce:
      pool:
        min-idle: 1
        max-idle: 64
        max-active: 64
        max-wait: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    serialization:
      indent-output: true
    time-zone: GMT+8
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  thymeleaf:
    mode: HTML
    cache: true

mybatis-plus: # ORM 组件
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    call-setters-on-nulls: true
    use-column-label: true
  type-aliases-package: org.ylzl.eden.demo.model.mapper

arthas: # 在线诊断工具
  agent-id: ${spring.application.name}@${random.value}
  tunnel-server: ws://localhost:7777/ws
  session-timeout: 1800
  telnet-port: 0
  http-port: 0
